### ISSUE TITLE
Version 3.1.0 is broken

### ISSUE THREAD

**Issue by turbo-time** [announcekitapp/announcekit-vue#20]
When building my app after moving to announcekit-vue 3.1.0 from 2.3.0, I get a build error:

```
X [ERROR] Could not read from file: C:\Users\turbo\source\repos\test\vue-2-project\vue\dist\vue.runtime.esm.js

    node_modules/announcekit-vue/dist/announcekit.es.js:1:56:
      1 │ import { nextTick, openBlock, createElementBlock } from "vue";
        ╵                                                         ~~~~~

C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/announcekit-vue/dist/announcekit.es.js:1:56: ERROR: Could not read from file: C:\Users\turbo\source\repos\test\vue-2-project\vue\dist\vue.runtime.esm.js
    at failureErrorWithLog (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1575:15)
    at C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1033:28
    at runOnEndCallbacks (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1447:61)
    at buildResponseToResult (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1031:7)
    at C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:1143:14
    at responseCallbacks.<computed> (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:680:9)
    at handleIncomingPacket (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:735:9)
    at Socket.readFromStdout (C:\Users\turbo\source\repos\test\vue-2-project\node_modules\esbuild\lib\main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: \'\',
      location: {
        column: 56,
        file: \'node_modules/announcekit-vue/dist/announcekit.es.js\',
        length: 5,
        line: 1,
        lineText: \'import { nextTick, openBlock, createElementBlock } from "vue";\',
        namespace: \'\',
        suggestion: \'\'
      },
      notes: [],
      pluginName: \'\',
      text: \'Could not read from file: C:\\Users\\turbo\\source\\repos\\test\\vue-2-project\\vue\\dist\\vue.runtime.esm.js\'
    }
  ],
  warnings: []
}

Node.js v18.12.1
```
After downgrading to 2.3.0 it works fine.

I tested this with Vue 2 (on Vite), with a new project built from running `npm init vue@2` .

**Comment by turbo-time** [comment]
This has since been remedied!
